# Misc. tests for python scripts

## TODO: fxi following error
## _s@ FROM=fr TO=en machine_translation.py 2>| /home/tomohara/temp/_qd_trans_spanish.20771.log /home/tomohara/temp/temp-run-command-20771-0.data
## ...
## 2023-07-12 13:20:43.829338: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
## ...
## ImportError: /home/tomohara/anaconda3/envs/nlp-py-3-9/lib/python3.9/site-packages/torch/lib/libc10_cuda.so: symbol cudaMemPoolSetAttribute version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference <<<
##----------
## check-errors /home/tomohara/mezcla/_franch-translation-error-12jul23.log
##
11   >>> 2023-07-12 13:20:44.455126: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/tomohara/lib::/home/tomohara/lib:/home/tomohara/lib/linux:/home/tomohara/lib::/home/tomohara/lib::/home/tomohara/lib:/home/tomohara/lib/linux:/home/tomohara/lib:/home/tomohara/lib/linux <<<
12   >>> 2023-07-12 13:20:44.455232: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/tomohara/lib::/home/tomohara/lib:/home/tomohara/lib/linux:/home/tomohara/lib::/home/tomohara/lib::/home/tomohara/lib:/home/tomohara/lib/linux:/home/tomohara/lib:/home/tomohara/lib/linux <<<
14   >>> Traceback (most recent call last): <<<
39   >>> ImportError: /home/tomohara/anaconda3/envs/nlp-py-3-9/lib/python3.9/site-packages/torch/lib/libc10_cuda.so: symbol cudaMemPoolSetAttribute version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference <<<
43   >>> Traceback (most recent call last): <<<
53   >>> RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback): <<<
